export const metadata: Metadata = {
  title: "Go and Learn | Contact",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

const Contact = () => {
  return <h1>Contact</h1>;
};

export default Contact;
