export const metadata: Metadata = {
  title: "Go and Learn | About",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

const About = () => {
  return <h1>About</h1>;
};

export default About;
